name: Build and Release APKs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: android-arm64
            name: arm64
          - platform: android-x64
            name: x64
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build APK for ${{ matrix.name }}
        run: flutter build apk --release --target-platform ${{ matrix.platform }}
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-${{ matrix.name }}-release.apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-apk
          path: build/app/outputs/flutter-apk/app-${{ matrix.name }}-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'latest-build' }}
          files: |
            build/app/outputs/flutter-apk/app-*-release.apk
